import '@fortawesome/fontawesome-free/css/all.min.css';
import { Inter } from 'next/font/google';
import PropTypes from 'prop-types';
import '../assets/styles/base/_reset.scss';
import { AlmContextProvider } from '../context/almContext';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => (
  <html lang="en">
    <body className={inter.className}>
      <AlmContextProvider>
        {children}
      </AlmContextProvider>
    </body>
  </html>
);

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};

export default RootLayout;
