import '@fortawesome/fontawesome-free/css/all.min.css';
// import { SessionProvider } from 'next-auth/react';
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { AlmContextProvider } from '@/context';
import { AuthProvider } from '@/context/authContext';
import { getServerSession } from "next-auth/next";
import { Outfit } from 'next/font/google';
import PropTypes from 'prop-types';
import '../assets/styles/base/_normalize.scss';
import '../assets/styles/base/_reset.scss';
import './globals.css';

const outfit = Outfit({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({ children }) => {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={outfit.className}>
        <AuthProvider>
          <AlmContextProvider>
            {children}
          </AlmContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};

export default RootLayout;
